version: '2'
services:
  db:
    user: "1000:50"
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_DATABASE: anemone
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - "6379:6379"
