spring:
  devtools:
    restart:
      additional-paths:
        - src/main/kotlin
  datasource:
    url: jdbc:mysql://192.168.99.102:3306/anemone
    username: root
    password: root
doma:
  dialect: mysql
