# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  devtools:
    restart:
      additional-paths:
        - src/main/kotlin
  datasource:
    url: jdbc:mysql:replication://localhost:3306,localhost:3306/anemone
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
doma:
  dialect: mysql
flyway:
  enabled: true